default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("MYSQL_MAX_THREADS") { 50 } %>
  reconnect: true

development:
  <<: *default
  host: us-cdbr-east-06.cleardb.net
  username: b88e968ae42645
  password: a01a5ff8
  database: heroku_09c99bed38708ae

test:
  <<: *default
  url: <%= ENV['TEST_DATABASE_URL'] %>

staging:
  <<: *default
  url: <%= ENV['STAGING_DATABASE_URL'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
  host: us-cdbr-east-06.cleardb.net
  username: b88e968ae42645
  password: a01a5ff8
  database: heroku_09c99bed38708ae